version: '3'
services:
  nginx:
    build: ./docker/nginx
    volumes:
      - ./src:/var/www/html
    ports:
      - '8006:80'
    depends_on:
      - php
  php:
    #image: php:7.3.6-fpm-alpine3.9
    image: itdevgroup/php-fpm7.4
    volumes:
      - ./src:/var/www/html
