<?php

return [
    'NGANLUONG_URL' => env('NGANLUONG_URL',''),
    'NGANLUONG_MERCHANT_ID' => env('NGANLUONG_MERCHANT_ID', ''),
    'NGANLUONG_MERCHANT_PASS' => env('NGANLUONG_MERCHANT_PASS', ''),
    'NGANLUONG_RECEIVER' => env('NGANLUONG_RECEIVER', '')
];
